[package]
name = "rouge-components"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
rouge-ansi.workspace = true
rouge-style.workspace = true
rouge-runtime.workspace = true
rouge-harmonica.workspace = true
unicode-width.workspace = true
unicode-segmentation.workspace = true
crossterm.workspace = true
