[package]
name = "ruse"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
ruse-ansi.workspace = true
ruse-colorprofile.workspace = true
ruse-harmonica.workspace = true
ruse-style.workspace = true
ruse-runtime.workspace = true
ruse-components.workspace = true
ruse-glamour.workspace = true
tokio.workspace = true

[features]
default = ["full"]
full = []

[[example]]
name = "counter"
path = "examples/counter.rs"

[[example]]
name = "todo"
path = "examples/todo.rs"

[[example]]
name = "textinput"
path = "examples/textinput.rs"

[[example]]
name = "viewport"
path = "examples/viewport.rs"

[[example]]
name = "spinner"
path = "examples/spinner.rs"

[[example]]
name = "composite"
path = "examples/composite.rs"
